/* -----------------------------------------------------------------------
   PORTRÉKÉPEK

   Ha a kepek/ mappában van kép az adott uralkodóhoz, az összeállításkor
   ide kerül adat-URI-ként, és a rajzolt arc helyett azt mutatjuk. Amelyik
   hiányzik, ott marad a rajzolt portré — a kettő keverhető.
   ----------------------------------------------------------------------- */
const RULER_IMG={};
const RIMG={};                                  // betöltött képek
/* A festmény betöltése aszinkron. A rulerImage csak akkor ad vissza képet,
   ha az már kész — ez a rajzoláshoz jó, de aki értesülni akar az
   érkezéséről, annak a nyers képre van szüksége. Enélkül a bemutatkozó
   képernyőn örökre a rajzolt tartalék maradt. */
function rulerImageRaw(nation,age){
  const key=nation+'-'+age, src=RULER_IMG[key];
  if(!src||typeof Image!=='function') return null;
  if(!RIMG[key]) rulerImage(nation,age);       // elindítja a betöltést
  return RIMG[key]||null;
}
function rulerImage(nation,age){
  const key=nation+'-'+age, src=RULER_IMG[key];
  if(!src||typeof Image!=='function') return null;
  let im=RIMG[key];
  if(!im){
    im=new Image();
    im.onload=()=>{
      drawPortrait();                            // sarokban lévő arckép
      const c=(typeof $==='function')?$('introPortrait'):null;   // bemutatkozó
      if(c&&typeof showIntroRepaint==='function') showIntroRepaint();
    };
    im.src=src;
    RIMG[key]=im;
  }
  return (im.complete&&im.naturalWidth)?im:null;
}

/* =======================================================================
   18/B. URALKODÓK

   Minden nemzethez négy korszak, minden korszakhoz egy uralkodó — huszonnyolc
   arc. A portréra kattintva rövid, tényszerű életrajz jelenik meg róluk.
   A 20. századi alakoknál a megítélés gyakran vitatott; ilyenkor ezt
   kimondjuk ahelyett, hogy elhallgatnánk vagy eldöntenénk.
   ===================================================================== */
const BIOS={
 ns:[
  {y:'1706–1718', k:'A Bahamák szigetén, Nassau kikötőjében néhány évre kalózköztársaság alakult: nem királynak, hanem közösen elfogadott kódexnek engedelmeskedtek.',
   t:'A spanyol örökösödési háború után kalózok ezrei maradtak munka nélkül, és Nassau kikötőjében gyűltek össze. Nem volt kormányzójuk: a hajókon szavazással választottak kapitányt, és írásba foglalt kódex szabta meg a zsákmány elosztását. A sebesülteknek kártérítés járt, a döntéseket a legénység hozta. 1718-ban a brit korona kegyelmet hirdetett, és Woodes Rogers kormányzó rendet tett — a Testvériség kora véget ért.'},
  {y:'1680 k.–1721', k:'Charles Vane volt az, aki nem fogadta el a király kegyelmét: égő hajót küldött a blokádra, és kivitorlázott Nassauból.',
   t:'Vane a kalózköztársaság legmakacsabb kapitánya volt. Amikor 1718-ban Woodes Rogers megérkezett a kegyelemlevéllel és a hadihajókkal, a többiek sorra letették a fegyvert — Vane viszont felgyújtott egy zsákmányolt francia hajót, nekiengedte a blokádnak, és a zűrzavarban kicsúszott a kikötőből. Kegyetlensége a saját legénységét is megosztotta: miután egy francia hadihajó elől kitért, a fedélzet gyávasággal vádolta és leszavazta a kapitányságról — a kódex ellene fordult. Kisebb hajóval folytatta, míg egy vihar partra vetette. Jamaicában ismerték fel, és 1721-ben Port Royalban felakasztották, testét vasketrecben állították ki a kikötő bejáratánál — figyelmeztetésül a következő nemzedéknek.'},
  {y:'1682 k.–1720', k:'Jack Rackham — „Calico Jack" — a tarka pamutruhájáról kapta a nevét, és a legismertebb kalózlobogót hagyta hátra.',
   t:'Rackham Vane kormányosa volt, és éppen ő szavaztatta le a kapitányt. Saját hajóján kis zsákmányokra vadászott a partok mentén, de a legénységébe két nő is bekerült: Anne Bonny és Mary Read. A koponya alatt keresztbe tett szablyát ábrázoló zászlaja lett a kalózkodás jelképe. 1720-ban egy angol őrhajó lepte meg őket, amikor a legénység nagy része részeg volt — a hagyomány szerint csak a két nő védekezett. Rackhamet Port Royalban akasztották fel.'},
  {y:'1697 k.–1782', k:'Anne Bonny a kevés név szerint ismert kalóznő egyike; ítéletét terhessége miatt felfüggesztették, és utána nyoma veszett.',
   t:'Bonny ír bevándorló lányaként került a Bahamákra, és Rackham legénységéhez csatlakozott — a hajón férfiruhában harcolt. Mary Read-del együtt őt is elfogták 1720-ban, és mindkettőjüket halálra ítélték, de mindketten terhesek voltak, ezért az ítéletet elhalasztották. Read börtönlázban meghalt; Bonny sorsáról nincs hiteles feljegyzés. Egy dél-karolinai hagyomány szerint az apja kiváltotta, és nyolcvanöt évesen halt meg — de ez sosem nyert bizonyítást.'}
 ],
 bb:[
  {y:'1680 körül–1718', k:'A leghírhedtebb kalóz. Csata előtt égő kanócokat font a szakállába, hogy füstben és szikrában jelenjen meg — a rettegés volt a fő fegyvere.',
   t:'Edward Teach kalózhajója, a Queen Anne bosszúja negyven ágyút hordozott. Módszere nem a mészárlás volt, hanem a félelemkeltés: aki megadta magát, azt rendszerint elengedte. 1718 tavaszán Charleston kikötőjét blokád alá vette, és váltságdíj helyett gyógyszerládát követelt. Ugyanabban az évben a Virginia kormányzója által küldött hajó legénysége Ocracoke szigeténél utolérte. A közelharcban esett el, alig két évnyi kalózkodás után.'},
  {y:'1680 körül–1718', k:'A leghírhedtebb kalóz.', t:'Edward Teach hajója, a Queen Anne bosszúja negyven ágyút hordozott. A rettegés volt a fő fegyvere: aki megadta magát, azt rendszerint elengedte. 1718-ban Ocracoke szigeténél esett el.'},
  {y:'1680 körül–1718', k:'A leghírhedtebb kalóz.', t:'Edward Teach hajója, a Queen Anne bosszúja negyven ágyút hordozott. A rettegés volt a fő fegyvere. 1718-ban Ocracoke szigeténél esett el.'},
  {y:'1680 körül–1718', k:'A leghírhedtebb kalóz.', t:'Edward Teach hajója, a Queen Anne bosszúja negyven ágyút hordozott. A rettegés volt a fő fegyvere. 1718-ban Ocracoke szigeténél esett el.'}
 ],
 sb:[
  {y:'1688–1718', k:'A kalózkodás történetének legfurcsább alakja: gazdag barbadosi földbirtokos, aki hajót VÁSÁROLT és fizetett legénységet fogadott — a mesterséghez viszont nem értett.',
   t:'Stede Bonnet ültetvényes volt és nyugalmazott őrnagy, amikor negyvenévesen kalóznak állt. Szemben a szokással, nem elrabolta a hajóját, hanem megvette, és a legénységnek fizetést adott — a kalózok között ez példátlan volt. Hajózáshoz nem értett, a legénysége kinevette. Egy ideig Fekete Szakáll mellé szegődött, aki gyakorlatilag elvette tőle a hajót. 1718-ban elfogták, és Charlestonban felakasztották. Az „úriember kalóz" néven maradt fenn.'},
  {y:'1688–1718', k:'Az úriember kalóz.', t:'Gazdag ültetvényes volt, aki negyvenévesen kalóznak állt: hajót vásárolt, és fizetést adott a legénységnek. Hajózáshoz nem értett. 1718-ban Charlestonban felakasztották.'},
  {y:'1688–1718', k:'Az úriember kalóz.', t:'Gazdag ültetvényes volt, aki negyvenévesen kalóznak állt: hajót vásárolt, és fizetést adott a legénységnek. 1718-ban Charlestonban felakasztották.'},
  {y:'1688–1718', k:'Az úriember kalóz.', t:'Gazdag ültetvényes volt, aki negyvenévesen kalóznak állt: hajót vásárolt, és fizetést adott a legénységnek. 1718-ban Charlestonban felakasztották.'}
 ],
 nat:[
  {y:'?–1500 körül', k:'A Karib-tenger szigeteinek népe, akik évszázadokkal az európaiak érkezése előtt telepedtek meg a szigetvilágban.',
   t:'A taíno közösségek falvakban éltek, pálmalevélből és fából emelt kunyhókban. Halásztak, maniókát és édesburgonyát termesztettek, és kenukkal jártak szigetről szigetre. A kacika, a falu vezetője egyszerre volt bíró, pap és hadvezér. Fegyverük a lándzsa, a bunkósbot és az íj volt; fémet nem használtak. Az európaiak érkezése után néhány évtized alatt a betegségek és a kényszermunka szinte teljesen elpusztította őket.'},
  {y:'?–1500 körül', k:'A szigetvilág őslakói.', t:'A taíno közösségek falvakban éltek, pálmalevélből és fából emelt kunyhókban. Halásztak és földet műveltek, kenukkal jártak szigetről szigetre. Fegyverük a lándzsa és az íj volt.'},
  {y:'?–1500 körül', k:'A szigetvilág őslakói.', t:'A taíno közösségek falvakban éltek, pálmalevélből és fából emelt kunyhókban. Halásztak és földet műveltek, kenukkal jártak szigetről szigetre. Fegyverük a lándzsa és az íj volt.'},
  {y:'?–1500 körül', k:'A szigetvilág őslakói.', t:'A taíno közösségek falvakban éltek, pálmalevélből és fából emelt kunyhókban. Halásztak és földet műveltek, kenukkal jártak szigetről szigetre. Fegyverük a lándzsa és az íj volt.'}
 ],
 es:[
  {y:'1452–1516', k:'Aragónia királya, aki Kasztíliai Izabellával kötött házassága révén egyesítette a spanyol koronákat. Az ő uralkodása alatt indult Kolumbusz nyugat felé, és fejeződött be a félsziget visszahódítása.',
   t:'Aragóniai Ferdinánd 1469-ben vette feleségül Kasztíliai Izabellát, és a két korona egyesítésével megszületett a modern Spanyolország alapja. 1492-ben Granada elfoglalásával lezárult a több évszázados reconquista. Ugyanabban az évben adott engedélyt egy genovai hajósnak, hogy nyugat felé keresse az Indiákat. A visszatérő hajók híre egész Európát megrázta. Uralkodása végére Spanyolország Európa első számú hatalmává vált.'},
  {y:'1527–1598', k:'A spanyol világbirodalom ura, akinek uralma alatt „soha nem ment le a nap". Flottája a Földközi-tengertől az Újvilágig ért, de az Armada pusztulása megtörte tengeri fölényét.',
   t:'II. Fülöp az Escorial dolgozószobájából kormányozta a világ addigi legnagyobb birodalmát. Uralkodása alatt érkezett Amerikából az ezüst, amely finanszírozta a háborúit, de el is értéktelenítette a pénzt. 1571-ben Lepantónál legyőzte az oszmán flottát. 1588-ban viszont az Anglia ellen indított Nagy Armada odaveszett a viharban és a csatákban. Élete végére a birodalom kimerült, de kiterjedése páratlan maradt.'},
  {y:'1716–1788', k:'A felvilágosult abszolutizmus spanyol uralkodója, aki utakat, csatornákat és iskolákat építtetett, és Madridot európai fővárossá formálta.',
   t:'III. Károly előbb Nápoly királya volt, onnan hozta magával a reformok iránti elkötelezettséget. Madridban utcákat köveztetett, közvilágítást és csatornahálózatot építtetett — kortársai „a legjobb polgármesternek" gúnyolták. Modernizálta a hadsereget és a gyarmati igazgatást, korlátozta az egyház hatalmát. A gyarmatokról érkező bevétel az ő idejében tetőzött. Halála után a napóleoni háborúk elsöpörték az általa épített rendet.'},
  {y:'1892–1975', k:'Spanyolország államfője a polgárháború végétől haláláig. A második világháborúból kimaradt, az országot évtizedekre elszigetelte, majd a hatvanas években gazdasági nyitást engedett.',
   t:'Francisco Franco katonatisztként emelkedett fel, és a polgárháborúból győztesen kikerülve közel négy évtizedig kormányozta Spanyolországot. A második világháborúban formálisan semleges maradt, így az ország kimaradt a pusztításból. Az ötvenes évekig nemzetközi elszigeteltségben élt, majd megállapodások nyitották meg a nyugati kaput. A hatvanas évek gazdasági fellendülése átalakította a spanyol társadalmat. Halála után az ország békés úton tért vissza a monarchiához és a demokráciához.'}
 ],
 hu:[
  {y:'1443–1490', k:'Magyarország királya 1458-tól haláláig, a magyar történelem egyik leghíresebb uralkodója. Megteremtette a zsoldosokból álló Fekete sereget, győzelmet aratott III. Frigyes csapatai felett, és uralkodása alatt virágzott fel a reneszánsz kultúra Budán — híres könyvtára, a Bibliotheca Corviniana Európa-szerte ismert volt.', t:'Hunyadi János fia, akit 1458-ban a nemesség választott királlyá, részben a Duna jegén összegyűlt sereg nyomására. Zsoldos alapon szervezte meg a fekete sereget, amely korának egyik legütőképesebb hadereje volt. Bécset 1485-ben elfoglalta, és élete végéig ott tartotta udvarát. Budai könyvtára, a Corvina, a reneszánsz Európa egyik leghíresebb gyűjteménye lett. Halála után a fekete sereg zsold híján felbomlott, és a birodalma is szétesett.'},
  {y:'1676–1735', k:'Erdély fejedelme, a Habsburg-ellenes magyar szabadságharc (1703–1711) vezérlő fejedelme. A kuruc felkelés élén állva küzdött a magyar rendek jogaiért és az ország önállóságáért; alakja a magyar nemzeti emlékezet egyik legnagyobb szabadsághőse.', t:'A leggazdagabb magyar főúr fiaként a bécsi udvar neveltetésében nőtt fel, mégis a Habsburg-ellenes felkelés élére állt. 1703-tól nyolc éven át vezette a kuruc szabadságharcot, amely idővel az ország nagy részét ellenőrzése alá vonta. Erdély és Magyarország fejedelmévé választották, de tartós külföldi szövetségest nem talált. A szatmári béke idején nem volt hajlandó hűséget esküdni, és emigrációba vonult. Élete végét a törökországi Rodostóban töltötte, ahonnan soha nem tért haza.'},
  {y:'1802–1894', k:'Politikus, újságíró, az 1848–49-es forradalom és szabadságharc legfőbb vezetője, a köztársaságra törekvő ország kormányzója. Szónoklataival tömegeket mozgósított; a vereség után emigrációban is a független Magyarország megtestesítője maradt.', t:'Ügyvédből lett politikus, akit már az 1830-as években bebörtönöztek a sajtószabadságért folytatott küzdelméért. 1848-ban pénzügyminiszterként ő teremtette elő a szabadságharc anyagi alapját, majd kormányzó-elnök lett. Az ő nevéhez fűződik a jobbágyfelszabadítás törvénybe iktatása és a honvédsereg megszervezése. A világosi fegyverletétel után emigrált, és soha nem tért vissza Magyarországra. Torinóban halt meg, temetése Budapesten százezreket vonzott.'},
  {y:'1868–1957', k:'Ellentengernagy, Magyarország kormányzója 1920 és 1944 között. Az első világháborúban tengeri győzelmeivel szerzett hírnevet; a két világháború közötti Magyarország államfőjeként hosszú évtizedekre meghatározta az ország politikáját.', t:'Az Osztrák–Magyar Monarchia flottájának utolsó főparancsnoka volt, majd 1920-tól huszonnégy éven át kormányzóként állt az ország élén. Nevéhez fűződik a trianoni békeszerződés utáni konszolidáció és a területi revízió politikája. Kormányzása alatt születtek a zsidótörvények, és Magyarország a második világháborúban a tengelyhatalmak oldalán lépett hadba. 1944-ben az ország német megszállása után nem akadályozta meg a vidéki zsidóság deportálását, a kiugrási kísérlete pedig elbukott. Megítélése máig az egyik legvitatottabb a magyar történelemben.'}
 ],
 at:[
  {y:'1415–1493', k:'Német-római császár 1452-től, a Habsburg-dinasztia első császára. Hosszú uralkodása alatt kezdődött a Habsburgok felemelkedése Európa vezető dinasztiájává; jelmondata, az A.E.I.O.U. máig rejtély és jelkép egyszerre.', t:'Ötvenhárom évig uralkodott, ezzel a leghosszabb ideig regnáló német-római császár. Kortársai határozatlannak tartották, ő maga inkább kivárt, mint harcolt. Mátyás elfoglalta előle Bécset, és élete nagy részében pénzhiánnyal küzdött. Fia, Miksa házasságával viszont megszerezte Burgundiát, és megalapozta a Habsburgok európai felemelkedését. Jelmondata, az A.E.I.O.U. betűsor máig megfejtetlen.'},
  {y:'1640–1705', k:'Német-római császár és magyar király, a barokk kor nagy Habsburg uralkodója. Uralkodása alatt zajlott Bécs 1683-as török ostroma, majd a török hatalom visszaszorítása; korában épült ki a barokk Bécs arculata.', t:'Eredetileg egyházi pályára szánták, császár csak bátyja korai halála után lett belőle. Uralkodását végigkísérte a kétfrontos háború: nyugaton XIV. Lajos, keleten az Oszmán Birodalom. 1683-ban Bécs ostroma alatt elhagyta a várost, amelyet a lengyel–német felmentő sereg mentett meg. A felszabadító háborúkban visszafoglalta a török hódoltság alatt álló Magyarországot. Uralkodása alatt tört ki a Rákóczi-szabadságharc is.'},
  {y:'1830–1916', k:'Osztrák császár és 1867 után magyar király, 1848-tól 68 éven át uralkodott. Neve összefonódott az Osztrák–Magyar Monarchia korával: birodalma fénykora és válságai egyaránt az ő hosszú uralkodása alatt zajlottak.', t:'Tizennyolc évesen került trónra a forradalmak évében, és hatvannyolc évig uralkodott. Fiatalon a magyar szabadságharc leverése és a megtorlás fűződik a nevéhez, később viszont ő írta alá az 1867-es kiegyezést. A Monarchia évtizedeit rendkívüli munkabírással és katonás napirenddel élte végig. Családi élete tragédiákkal volt tele: fia öngyilkos lett, feleségét meggyilkolták. Az ő aláírásával indult az első világháború, amelynek végét már nem érte meg.'},
  {y:'1887–1922', k:'Az Osztrák–Magyar Monarchia utolsó császára és magyar királya (1916–1918). Békepróbálkozásai az első világháborúban eredménytelenek maradtak; a birodalom szétesése után száműzetésbe kényszerült.', t:'Az utolsó osztrák császár és magyar király, aki 1916-ban, a háború közepén került trónra. Uralkodása mindössze két évig tartott, és végig a béke megkötésével próbálkozott. Titkos tárgyalásai kitudódtak, ami szövetségesei előtt is hitelét vesztette. 1918-ban lemondott az államügyekben való részvételről, de a trónról soha. Két visszatérési kísérlete után Madeirára száműzték, ahol harmincnégy évesen tüdőgyulladásban meghalt.'}
 ],
 pl:[
  {y:'1427–1492', k:'Jagelló-házi lengyel király és litván nagyfejedelem. Uralkodása alatt Lengyelország európai nagyhatalommá vált: a tizenhárom éves háborúban legyőzte a Német Lovagrendet, és a porosz területek a korona fennhatósága alá kerültek.', t:'A Jagelló-ház tagjaként Litvánia nagyfejedelme, majd Lengyelország királya lett. Uralkodása alatt a lengyel–litván állam Európa egyik legnagyobb kiterjedésű hatalmává vált. A tizenhárom éves háborúban legyőzte a Német Lovagrendet, és megszerezte a Balti-tengerhez vezető utat. Gyermekei több európai trónra kerültek, köztük a magyarra és a csehre is. A nemesség jogait bővítette, ami később az állam gyengeségének is forrása lett.'},
  {y:'1629–1696', k:'Lengyel király, kiváló hadvezér. 1683-ban a szárnyas huszárok rohamával felmentette a törökök által ostromolt Bécset — ezzel a győzelemmel írta be magát Európa történelmébe.', t:'Katonaként emelkedett fel, és hadvezéri hírneve juttatta a trónra. 1683-ban ő vezette a Bécset felmentő keresztény sereget, és a kahlenbergi lovasrohammal döntötte el a csatát. A győzelem után küldött üzenete — jöttem, láttam, Isten győzött — az európai emlékezet része lett. Otthon viszont nem tudta megtörni a nemesi ellenállást és a szabad királyválasztás rendszerét. Halála után az ország hanyatlásnak indult.'},
  {y:'1746–1817', k:'Lengyel tábornok és nemzeti hős, az 1794-es felkelés vezetője a Lengyelország felosztása ellen. Korábban az amerikai függetlenségi háborúban is harcolt; alakja a szabadság jelképe több nemzeten át.', t:'Katonai mérnökként az amerikai függetlenségi háborúban szolgált, ahol erődítményei döntőnek bizonyultak. Hazatérve az 1794-es felkelés vezetője lett Oroszország és Poroszország ellen. Kaszákkal felfegyverzett parasztokat is beépített a hadseregébe, ami korában szokatlan volt. A felkelés bukása után orosz fogságba került, majd emigrációban élt. Végrendeletében amerikai vagyonát rabszolgák felszabadítására hagyta.'},
  {y:'1867–1935', k:'Tábornok, államférfi, az 1918-ban újjászülető Lengyelország egyik alapítója és első államfője. A csodaként emlegetett varsói csatában 1920-ban megállította a szovjet előnyomulást.', t:'Fiatalon szocialista forradalmárként harcolt a cári uralom ellen, és többször bebörtönözték. Az első világháborúban légiókat szervezett, majd 1918-ban az újjászülető Lengyelország államfője lett. 1920-ban a varsói csatában megállította a szovjet előrenyomulást. 1926-ban katonai puccsal vette át a hatalmat, és haláláig tekintélyelvű rendszert működtetett. Megítélése kettős: az ország megmentőjeként és a demokrácia felszámolójaként egyaránt számon tartják.'}
 ],
 de:[
  {y:'1459–1519', k:'Német-római császár, az utolsó lovagnak nevezett uralkodó. Házassági politikájával a Habsburgok világhatalmának alapjait vetette meg, és megújította a birodalom intézményeit.', t:'Burgundi házassága révén szerzett vagyont és területet, ezzel megalapozta a Habsburgok hatalmát. Császárként a birodalmi közigazgatás és az állandó hadsereg megteremtésén dolgozott. Nevéhez fűződik a landsknecht gyalogság megszervezése, amely a korszak harcmodorát átalakította. Unokái számára házasságokkal szerzett spanyol és magyar trónigényt. Az utolsó lovagnak nevezték, miközben a hadviselést már a tűzfegyverek felé terelte.'},
  {y:'1620–1688', k:'Brandenburg választófejedelme, a Nagy Választófejedelem. A harmincéves háború pusztítása után megszervezett hadseregével és gazdaságpolitikájával Poroszország későbbi királyságának alapjait teremtette meg.', t:'Brandenburg választófejedelme, akit Nagy Választófejedelemként emlegetnek. Egy háborúban kifosztott, széttagolt tartományt örökölt, és állandó hadsereget épített belőle. Adóztatási és közigazgatási reformjaival a porosz állam alapjait rakta le. Vallási menekülteket, köztük francia hugenottákat telepített be, ami fellendítette a gazdaságot. Utódai az ő hadseregére támaszkodva emelték királysággá Poroszországot.'},
  {y:'1815–1898', k:'Porosz államférfi, a vaskancellár. 1871-ben egyetlen császársággá egyesítette a német államokat, és az új Német Birodalom első kancellárjaként évtizedekre meghatározta Európa erőviszonyait.', t:'Porosz miniszterelnökként vér és vas politikájával három háborút vívott meg tizenegy év alatt. 1871-ben Versailles-ban kikiáltotta a Német Császárságot, és annak első kancellárja lett. Bonyolult szövetségi rendszerrel tartotta egyensúlyban Európát, és tartósan elszigetelte Franciaországot. Otthon üldözte a szociáldemokratákat, ugyanakkor ő vezette be a világ első állami betegbiztosítását és nyugdíjrendszerét. Az új császár 1890-ben menesztette, és a rendszere nélküle borult fel.'},
  {y:'1847–1934', k:'Német tábornagy az első világháborúban, a tannenbergi csata győztese, majd a weimari köztársaság elnöke 1925-től 1934-ig; a német történelem viharos korszakának egyik kulcsfigurája.', t:'Nyugdíjazott tábornokként hívták vissza 1914-ben, és a tannenbergi győzelem országos hőssé tette. A háború második felében Ludendorff-fal együtt gyakorlatilag katonai diktatúrát vezetett. A vereség után ő terjesztette a tőrdöfés-legendát, amely a polgári politikusokra hárította a felelősséget. 1925-ben a Weimari Köztársaság elnökévé választották, bár a köztársaságot maga sem szerette. 1933 januárjában ő nevezte ki Hitlert kancellárrá — ez a döntése máig a huszadik század egyik legsúlyosabb következményű lépése.'}
 ],
 fr:[
  {y:'1423–1483', k:'Francia király, a pókkirály. Ravasz diplomáciájával megtörte Burgundia hatalmát és nagyobbrészt egyesítette a francia területeket — vele kezdődik a modern francia állam kialakulása.', t:'Az egyetemes pók néven emlegették, mert diplomáciával és megvesztegetéssel dolgozott, nem csatákkal. Legyőzte a burgundi herceget, és a széttagolt hűbérbirtokokból egységes királyi hatalmat épített. Létrehozta az első állandó francia postaszolgálatot. Gyanakvó természete miatt élete végén szinte elzárkózott a világtól. Uralkodása alatt Franciaország a középkori hűbériségből a központosított állam felé lépett.'},
  {y:'1638–1715', k:'A Napkirály, 72 évig uralkodott — a leghosszabb ideig Európa történetében. Megépítette Versailles-t, és az abszolút monarchia megtestesítőjévé vált.', t:'A Napkirály hetvenkét évig uralkodott, ez a leghosszabb regnálás az európai történelemben. Versailles-ba költöztette az udvart, és a nemességet ott tartva fosztotta meg önálló hatalmától. Négy nagy háborút viselt, amelyek kiterjesztették a határokat, de kimerítették a kincstárat. A nantes-i ediktum visszavonásával több százezer hugenottát üldözött el az országból. Az abszolút uralkodó mintaképe lett egész Európa számára.'},
  {y:'1769–1821', k:'Korszakos hadvezér, 1804-től a franciák császára. Hadjárataival átrajzolta Európa térképét, polgári törvénykönyve pedig máig a modern jogrendek alapja.', t:'Korzikai kisnemesi családból tüzértisztként indult, és a forradalom zűrzavarában emelkedett a csúcsra. 1804-ben császárrá koronázta magát, és Európa nagy részét ellenőrzése alá vonta. Hadvezéri újításai — a gyors menetelés és a tüzérség tömeges bevetése — átalakították a hadviselést. Polgári törvénykönyve máig számos ország jogrendszerének alapja. Az oroszországi hadjárat és Waterloo után Szent Ilona szigetén halt meg.'},
  {y:'1890–1970', k:'Tábornok és államférfi, a második világháborúban a Szabad Franciaország vezetője, az Ötödik Köztársaság alapítója és elnöke; a francia nemzeti önállóság jelképe.', t:'Páncélos szakértő tisztként már a harmincas években a gépesített hadviselés mellett érvelt. 1940-ben, a francia összeomlás után Londonból szólította fel honfitársait az ellenállásra. A háború végén ő vezette a felszabadult Franciaország ideiglenes kormányát, majd visszavonult. 1958-ban az algériai válság idején tért vissza, és megalapította az ötödik köztársaságot. Önálló francia atomerőt és külpolitikát épített, gyakran szembemenve az amerikai szövetségesekkel.'}
 ],
 gb:[
  {y:'1457–1509', k:'Az első Tudor-házi angol király. A rózsák háborúját lezárva teremtett békét és erős királyi hatalmat, megalapozva Anglia felemelkedését a 16. századra.', t:'A bosworthi csatában legyőzte III. Richárdot, és ezzel lezárta a rózsák háborúját. York Erzsébettel kötött házassága egyesítette a két rivális házat. Uralkodása alatt a kincstárat rendbe hozta, és a nemesi magánhadseregeket felszámolta. Kereskedelmi szerződésekkel és óvatos külpolitikával erősítette az országot. A Tudor-ház alapítójaként stabil államot hagyott a fiára.'},
  {y:'1599–1658', k:'Az angol polgárháború vezéralakja, I. Károly kivégeztetése után a köztársaság feje; puritán szigora és katonai tehetsége máig vitatott alakja az angol történelemnek.', t:'Vidéki földbirtokosból lett a polgárháború legeredményesebb parancsnoka. Új mintájú hadserege fegyelmével és képzettségével döntötte el a küzdelmet. 1649-ben aláírta I. Károly halálos ítéletét, ezzel Anglia rövid időre köztársaság lett. Lordprotektorként gyakorlatilag egyeduralkodóként kormányzott, a parlamentet többször feloszlatva. Írországi hadjárata máig súlyos emléke az ír történelemnek.'},
  {y:'1819–1901', k:'Az Egyesült Királyság királynője 1837-től 63 éven át. Uralkodása alatt vált a Brit Birodalom a világ legnagyobb hatalmává — az egész korszak az ő nevét viseli.', t:'Tizennyolc évesen került trónra, és hatvannégy évig uralkodott — a viktoriánus kor róla kapta a nevét. Uralkodása alatt a Brit Birodalom a világ területének negyedére terjedt ki. Az ipari forradalom, a vasút és a gyarmati terjeszkedés évtizedei ezek. Férje, Albert halála után évtizedekig gyászban élt, és visszavonult a nyilvánosságtól. A korszakot a technikai fejlődés és a mély társadalmi egyenlőtlenség egyszerre jellemezte.'},
  {y:'1874–1965', k:'Miniszterelnök a második világháború éveiben; híres beszédeivel és hajthatatlanságával a náci Németország elleni küzdelem jelképévé vált. Irodalmi Nobel-díjas szerző is egyben.', t:'Katonaként, haditudósítóként és politikusként is dolgozott, pályája tele volt bukásokkal. 1940-ben, a legreménytelenebb pillanatban lett miniszterelnök, és beszédeivel tartotta a lelket az országban. Elutasította a Hitlerrel kötendő különbékét, és kitartott a szövetségesek mellett. A háború után a vasfüggöny kifejezéssel írta le Európa kettéosztottságát. Irodalmi Nobel-díjat kapott, gyarmati kérdésekben vallott nézeteit viszont ma sokan bírálják.'}
 ],
 ru:[
  {y:'1440–1505', k:'Moszkva nagyfejedelme, a Nagy. Lerázta a mongol–tatár uralmat, megháromszorozta a Moszkvai Fejedelemség területét, és megteremtette az egységes orosz állam alapjait.', t:'Moszkva nagyfejedelme, aki egyesítette az orosz fejedelemségeket. 1480-ban véget vetett a tatár uralomnak, anélkül hogy csatát kellett volna vívnia. Bizánci hercegnőt vett feleségül, és átvette a kétfejű sast jelképként. Olasz építészekkel emeltette a moszkvai Kreml ma is álló falait. Ő használta először az összes oroszok uralkodója címet.'},
  {y:'1672–1725', k:'Cár, 1721-től orosz császár. Nyugati mintára modernizálta az országot, flottát és új fővárost, Szentpétervárt alapította; Oroszországot európai nagyhatalommá tette.', t:'Fiatalon álruhában járta be Nyugat-Európát, ahol hajóácsként is dolgozott. Hazatérve erőszakos gyorsasággal alakította át az orosz államot, a hadsereget és még a viseletet is. Megalapította Szentpétervárt egy mocsaras torkolatban, hatalmas emberáldozat árán. A svédek felett aratott poltavai győzelmével Oroszország nagyhatalommá vált. Reformjai modernizáltak, ugyanakkor a jobbágyság terheit is súlyosbították.'},
  {y:'1777–1825', k:'Orosz császár, aki 1812-ben feltartóztatta és legyőzte Napóleont. A napóleoni háborúk utáni európai békerend, a Szent Szövetség egyik fő alakítója.', t:'Nagyanyja, Nagy Katalin neveltetésében nőtt fel, felvilágosult eszmékkel. Uralkodása elején reformokat tervezett, de a legtöbbet nem valósította meg. 1812-ben Napóleon inváziójával szemben a visszavonulás és a felperzselt föld taktikáját választotta. Csapatai 1814-ben bevonultak Párizsba, ő maga a Szent Szövetség létrehozója lett. Élete végén misztikus vallásosságba fordult, halála körül máig legendák keringenek.'},
  {y:'1868–1918', k:'Az utolsó orosz cár (1894–1917). Az első világháború és a forradalmak sodrában lemondott a trónról; 1918-ban családjával együtt kivégezték — vele ért véget a Romanovok háromszáz éves uralma.', t:'Az utolsó orosz cár, aki saját bevallása szerint sem készült az uralkodásra. Az orosz–japán háború veresége és a véres vasárnap megrendítette a rendszer tekintélyét. Az első világháborúban személyesen vette át a hadsereg vezetését, ezzel magára vonta a kudarcok felelősségét. 1917-ben lemondott, és a Romanov-dinasztia háromszáz éves uralma véget ért. Családjával együtt a bolsevikok végezték ki Jekatyerinburgban.'}
 ]
};
// A portréra kattintva jelenik meg, és bárhová kattintva bezárul
function showBio(){
  /* A szöveg a NYELVNEK megfelelő változatban jön (22d-rulers-lang.js).
     Ha az adott nyelvhez nincs fordítás, a magyar marad. */
  const n=NATIONS[G.nation];
  const b=(typeof bioSzoveg==='function')?bioSzoveg(G.nation,G.age)
          :(BIOS[G.nation]&&BIOS[G.nation][G.age]);
  if(!b) return;
  $('bioName').textContent=uralkodoNev(G.nation,G.age);
  $('bioMeta').textContent=b.y+' · '+allamForma(G.nation,G.age)+' · '+korszakNev(G.age);
  $('bioLead').textContent=b.k||'';
  $('bioText').textContent=b.t;
  $('bio').style.display='block';
  announce(uralkodoNev(G.nation,G.age)+'. '+(b.k||'')+' '+b.t);
  SFX.play('click');
}
function hideBio(){ const e=$('bio'); if(e) e.style.display='none'; }
